config/routes.rb
Rails.application.routes.draw do
  get 'make_my_trip_bookings/new'
  get 'make_my_trip_bookings/search', to: 'make_my_trip_bookings#search', as: :search_buses
  get 'make_my_trip_bookings/search_suggestion'
  get 'ticket_bookings/new'
  get 'ticket_bookings/create'
  devise_for :users
  ActiveAdmin.routes(self)
  root to: "home#index"
  resources :payments
  get 'home/index'
  resources :tickets do
    resources :ticket_bookings, only: [:new, :create]
  end
  resources :users do
    get 'my_tickets', on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :booked_tickets, class_name: 'Ticket', foreign_key: 'booked_by_id', dependent: :destroy
  has_many :received_tickets, class_name: 'Ticket', foreign_key: 'booked_for_id', dependent: :destroy

  enum relationship: { friends: 'Friends', colleagues: 'Colleagues' }
  validates :name, presence: true
  before_save :customize_name

  private
  def customize_name
    customized_name = self.name.downcase
    name_array = customized_name.split(" ")
    if name_array.size >= 2
      self.name = "#{name_array.first.capitalize} #{name_array.last.capitalize}"
    else
      self.name = "#{name_array.first.capitalize}"
    end
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!

  before_action :set_user, only: %i[ show edit update destroy ]

  # GET /users or /users.json
  def index
    @users = User.all
  end

  # GET /users/1 or /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users or /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to user_url(@user), notice: "User was successfully created." }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end

  end

  # PATCH/PUT /users/1 or /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to user_url(@user), notice: "User was successfully updated." }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1 or /users/1.json
  def destroy
    @user.destroy

    respond_to do |format|
      format.html { redirect_to users_url, notice: "User was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  def my_tickets
    @user_tickets = Ticket.where("booked_by_id = ? OR booked_for_id = ?", current_user.id, current_user.id).sort.reverse
  end
  
  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def user_params
      params.require(:user).permit(:name)
      # params.fetch(:user, {})
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_with(model: user) do |form| %>
  <% if user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
        <% user.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="actions">
    <div class="form-outline form-white mb-4">
      <%= form.label :name, class: "text-white-50 mb-1" %>
      <%= form.text_field :name, class: "form-control form-control-sm field-label", autofocus: true, autocomplete: "name", placeholder: "Enter Your Name" %>
    </div>
    <%= form.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<!-- app/views/users/edit.html.erb -->
<div id="edit-user">
  <h1>Editing User</h1>

  <%= render 'form', user: @user %>

  <div class="user-actions">
    <%= link_to 'Show', @user, class: 'btn btn-primary' %> |
    <%= link_to 'Back', users_path, class: 'btn btn-secondary' %> |
    <%= link_to 'Home', root_path, class: 'btn btn-secondary' %>
  </div>
</div>

app/views/users/index.html.erb
<!-- app/views/users/index.html.erb -->
<div id="users-list">
  <p id="notice"><%= notice %></p>

  <h1>Users</h1>

  <table>
      <tr>
        <th>Name</th>
        <th colspan="3">Actions</th>
      </tr>

    <tbody>
      <% @users.each do |user| %>
        <tr>
          <td><%= user.name %></td>
          <td><%= link_to 'Show', user, class: 'btn' %></td>
          <%# <td><%= link_to 'Edit', edit_user_path(user), class: 'btn' %></td>
           <td><%= button_to 'Delete ', user, method: :delete, data: { confirm: 'Are you sure?', class: 'btn btn-danger' } %> %>
          <%#= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>
  <%= link_to 'Home', root_path, class: 'btn btn-primary' %>
  <%= link_to 'New User', new_user_path, class: 'btn btn-primary' %>
</div>

app/views/users/my_tickets.html.erb
<div class="text-center">
  <div class="card">
    <div class="card-body">
      <p>You can add details to tickets, once you add details to a ticket the owner will receive an email with all the journey details.</p>
      <%= form_tag(ticket_bookings_new_path, method: :get, class: "ticket-details-form") do %>
        <div class="form-group">
          <%= label_tag :ticket_id, "Select a Ticket Week to Add Details", class: "control-label" %>
          <%= select_tag(:ticket_id, options_for_select(@user_tickets.map { |t| [t.week_date, t.id] }), prompt: "Select a ticket", class: "form-control custom-select") %>
        </div>
        <%= submit_tag "Add/Save Details", class: "btn1 btn-primary btn-block" %>
      <% end %>
    </div>
  </div>
  <div class="user-actions">
    <%= link_to 'Home', root_path, class: 'btn btn-secondary btn-block' %>
  </div>
</div>

<style type="text/css">
  .text-center {
  text-align: center;
}

.card {
  max-width: 400px;
  margin: 0 auto;
  border-radius: 10px;
  box-shadow: 0 4px 6px rgba(0, 0, 0, 0.1);
}

.card-body {
  padding: 20px;
}

.control-label {
  font-weight: bold;
}

.form-control {
  width: 100%;
  height: 40px;
  padding: 10px;
  font-size: 16px;
  border-radius: 5px;
  border: 1px solid #ccc;
}

.custom-select {
  appearance: none;
  -webkit-appearance: none;
  -moz-appearance: none;
  background: url('data:image/svg+xml;utf8,<svg xmlns="http://www.w3.org/2000/svg" width="12" height="12" viewBox="0 0 24 24" fill="none" stroke="%23707070" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"><polyline points="6 9 12 15 18 9"></polyline></svg>') no-repeat right 10px center/12px;
  padding-right: 30px;
}

.btn1 {
  margin-top: 25px;
  display: block;
  width: 100%;
  height: 40px;
  line-height: 25px;
  font-size: 16px;
  text-align: center;
  color: #fff;
  border: none;
  border-radius: 5px;
  cursor: pointer;
  transition: background-color 0.3s ease;
}

</style>

app/views/users/new.html.erb
<!-- app/views/users/new.html.erb -->
<div id="new-user">
  <h1>New User</h1>

  <%= render 'form', user: @user %>

  <div class="user-actions">
    <%= link_to 'Back', users_path, class: 'btn' %>
    <%= link_to 'Home', root_path, class: 'btn' %>
  </div>
</div>

app/views/users/show.html.erb
<!-- app/views/users/show.html.erb -->
<div id="user-details">
  <p id="notice"><%= notice %></p>
  <div class="user-info">
    <span class="user-label">Name:</span>
    <span class="user-name"><%= @user.name %></span>
  </div>
  <div class="user-actions">
    <%= link_to 'Edit', edit_user_path(@user), class: 'btn' %> |
    <%= link_to 'Back', users_path, class: 'btn' %> |
    <%= link_to 'Home', root_path, class: 'btn' %>
  </div>
</div>