config/routes.rb
Rails.application.routes.draw do
  get 'make_my_trip_bookings/new'
  get 'make_my_trip_bookings/search', to: 'make_my_trip_bookings#search', as: :search_buses
  get 'make_my_trip_bookings/search_suggestion'
  get 'ticket_bookings/new'
  get 'ticket_bookings/create'
  devise_for :users
  ActiveAdmin.routes(self)
  root to: "home#index"
  resources :payments
  get 'home/index'
  resources :tickets do
    resources :ticket_bookings, only: [:new, :create]
  end
  resources :users do
    get 'my_tickets', on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  before_action :authenticate_user!

  def index
    @payments = Payment.where("paid_to_id = ? OR paid_by_id = ?", current_user.id, current_user.id).order(updated_at: :desc)
    @payment = @payments.order(updated_at: :desc).first
    # @payment = Payment.order(updated_at: :desc).first
    # @owe_summary = calculate_owe_summary
    @owe_summary = HomeController.calculate_owe_summary(current_user)
  end

  # def self.calculate_owe_summary
  #   owe_summary = Hash.new(0)

  #   Ticket.all.each do |ticket|
  #     booked_by = ticket.booked_by
  #     booked_for = ticket.booked_for
  #     relationship = "Friends"
  #     if ticket.price_per_ticket == 85
  #       total_amount = ticket.booked_count * 85 + ticket.extra_charges
  #     else
  #       total_amount = ticket.booked_count * ticket.price_per_ticket + ticket.extra_charges
  #     end

  #     if relationship == 'Friends'
  #       owe_summary[booked_by] -= total_amount
  #       owe_summary[booked_for] += total_amount
  #     elsif relationship == 'Colleagues'
  #       owe_summary[booked_by] += total_amount
  #       owe_summary[booked_for] -= total_amount
  #     end
  #   end

  #   Payment.all.each do |payment|
  #     owe_summary[payment.paid_by] -= payment.amount
  #     owe_summary[payment.paid_to] += payment.amount
  #   end
  #   owe_summary
  # end
  def self.calculate_owe_summary(current_user)
    owe_summary = Hash.new(0)

    Ticket.where("booked_by_id = ? OR booked_for_id = ?", current_user.id, current_user.id).each do |ticket|
      total_amount = ticket.booked_count * ticket.price_per_ticket + ticket.extra_charges

      if ticket.booked_by_id == current_user.id
        owe_summary[ticket.booked_for_id] += total_amount
      elsif ticket.booked_for_id == current_user.id
        owe_summary[ticket.booked_by_id] -= total_amount
      end
    end

    Payment.where("paid_by_id = ? OR paid_to_id = ?", current_user.id, current_user.id).each do |payment|
      if payment.paid_by_id == current_user.id
        owe_summary[payment.paid_to_id] += payment.amount
      elsif payment.paid_to_id == current_user.id
        owe_summary[payment.paid_by_id] -= payment.amount
      end
    end

    owe_summary.reject! { |_, value| value.zero? }

    owe_summary
  end
end

app/helpers/home_helper.rb
module HomeHelper
end

app/views/home/index.html.erb
<%= stylesheet_link_tag 'home', media: 'all', 'data-turbolinks-track': 'reload' %>

<style>
  body {
    font-family: 'Segoe UI', Tahoma, Geneva, Verdana, sans-serif;
    background-color: #f8f9fa;
    margin: 0;
    padding: 0;
    color: #333;
  }

  #owe-summary {
    margin-top: 20px;
  }

  .owe-item {
    background-color: #fff;
    border: 1px solid #ddd;
    border-radius: 5px;
    margin-bottom: 10px;
    padding: 15px;
  }

  .user-name {
    font-weight: bold;
    margin-right: 10px;
  }

  .amount {
    color: green;
  }

  .zero {
    background-color: #e0e0e0;
    color: #555;
  }

  .btn-container {
    text-align: center;
    margin-top: 20px;
  }

  .btn {
    display: inline-block;
    padding: 12px 20px;
    margin: 10px;
    text-decoration: none;
    background-color: lightblue;
    color: #fff;
    border: none;
    border-radius: 5px;
    font-size: 16px;
    cursor: pointer;
    transition: background-color 0.3s;
  }

  .btn:hover {
    background-color: lightcyan;
  }

  .recent-payment {
    background-color: #fff;
    border: 1px solid #ddd;
    border-radius: 5px;
    padding: 15px;
    margin-top: 20px;
  }
    h3{
      text-align: center;
   font-weight: 150x;
   margin-bottom: 10px;
   font-size: 25px;
   position: relative;
<%#    -webkit-text-stroke: 1px #3E6469; %>
   color: lightseagreen;
  }

  h3::after {
    content: "";
    position: absolute;
    left: 0;
    bottom: 0;
    height: 3px;
    width: 0%;
    background-color: lightblue;
    transition: all ease 1s;
  } 
</style>

<div id="owe-summary">
  <h3 style="margin-bottom: 10px">Hey! <%= current_user.name%></h3>
  <% if @owe_summary.present? %>
    <% @owe_summary.each do |user_id, amount| %>
      <% user = User.find(user_id) %>
      <div class="owe-item <%= amount > 0 ? 'positive' : 'negative' %>">
        <span class="amount">
          <% if amount > 0 %>
           <%# <span class="user-name"></span> %>
           <b><%= user.name %></b>
            has to pay <b>You</b> <i style="color: red; font-size: 15px; font-family: Montserrat, sans-serif;"> ₹<%= amount.abs %>.</i>
          <% else %>
            <%# <span class="user-name"> You </span> %>
            <b> You </b> have to pay <b><%= user.name %></b> <i style="color: red; font-size: 15px; font-family: Montserrat, sans-serif;">₹<%= amount.abs %>.</i>
          <% end %>
        </span>
      </div>
    <% end %>
  <% else %>
    <div class="owe-item zero">
      <span class="amount">You don't have to pay or take anything from anyone.</span>
    </div>
  <% end %>
</div>


<div class="btn-container">
  <%= link_to 'Book on MMT', make_my_trip_bookings_new_path, class: 'btn' %>
  <%= link_to 'Add New Ticket', new_ticket_path, class: 'btn' %>
  <%= link_to 'Save Tickets Details', my_tickets_users_path, class: 'btn' %>
  <%= link_to 'Show Previous Tickets', tickets_path, class: 'btn' %>
  <%= link_to 'Add New Payment', new_payment_path, class: 'btn' %>
  <%= link_to 'Show Previous Payments', payments_path, class: 'btn' %>
</div>

<div class="recent-payment <%= @payment.present? ? 'positive' : 'zero' %>">
  <% if @payment.present? %>
    Recently <b><%= @payment.paid_by.name %></b> paid ₹<%= @payment.amount %> to <b><%= @payment.paid_to.name %></b> on <%= @payment.date %>
  <% else %>
    No recent payments.
  <% end %>
</div>