config/routes.rb
Rails.application.routes.draw do
  get 'make_my_trip_bookings/new'
  get 'make_my_trip_bookings/search', to: 'make_my_trip_bookings#search', as: :search_buses
  get 'make_my_trip_bookings/search_suggestion'
  get 'ticket_bookings/new'
  get 'ticket_bookings/create'
  devise_for :users
  ActiveAdmin.routes(self)
  root to: "home#index"
  resources :payments
  get 'home/index'
  resources :tickets do
    resources :ticket_bookings, only: [:new, :create]
  end
  resources :users do
    get 'my_tickets', on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/ticket.rb
# app/models/ticket.rb
class Ticket < ApplicationRecord
  # after_create :send_ticket_created_email
  # after_update :send_ticket_created_email
  belongs_to :user
  belongs_to :booked_by, class_name: 'User', foreign_key: 'booked_by_id', optional: true
  belongs_to :booked_for, class_name: 'User', foreign_key: 'booked_for_id', optional: true
  has_many :ticket_bookings, dependent: :destroy

  validates :user_id, :booked_by, :booked_for, :week_date, presence: true  
  validates :booked_count, presence: true
  validates :extra_charges, numericality: { greater_than_or_equal_to: 0 }
  validates :week_date, presence: true
  validate :different_user_and_booked_by
  validate :different_user_and_booked_for
  validate :unique_week#, on: :create

  def send_ticket_created_email(current_user)
    booked_by = User.find(self.booked_by_id)
    booked_for = User.find(self.booked_for_id)
    TicketMailer.ticket_created_email(self, HomeController.calculate_owe_summary(booked_by), booked_by).deliver_now
    TicketMailer.ticket_created_email(self, HomeController.calculate_owe_summary(booked_for), booked_for).deliver_now
    # TicketMailer.ticket_created_email(self, HomeController.calculate_owe_summary(current_user), current_user).deliver_now
  end

  private

  def different_user_and_booked_by
    if booked_by_id.present? && user_id != booked_by_id
      errors.add(:booked_by_id, "should be same as user")
    end
  end 

  def different_user_and_booked_for
    if booked_for_id.present? && user_id == booked_for_id
      errors.add(:booked_for_id, "should be different from user")
    end
  end

  def unique_week
    existing_ticket = Ticket.where.not(id: id).find_by(user_id: user_id, booked_for_id: booked_for_id, week_number: week_number, year: year)
    # existing_ticket = Ticket.find_by(user_id: user_id, booked_for_id: booked_for_id, week_number: week_number, year: year)
    # existing_ticket = Ticket.where.not(id: id, booked_for: booked_for).find_by(week_number: week_number, year: year, user_id: user_id)

    if existing_ticket.present?
      errors.add(:base, "Tickets for the week of selected date are already booked")
    end
  end
end

app/controllers/tickets_controller.rb
class TicketsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_ticket, only: %i[ show edit update destroy ]

  # GET /tickets or /tickets.json
  # def index
  #   @tickets = Ticket&.all&.sort&.reverse
  # end
   def index
    @tickets = Ticket.where("booked_by_id = ? OR booked_for_id = ?", current_user.id, current_user.id).sort.reverse
  end

  # GET /tickets/1 or /tickets/1.json
  def show
  end

  # GET /tickets/new
  def new
    @ticket = Ticket.new
  end

  # GET /tickets/1/edit
  def edit
  end

  # POST /tickets or /tickets.json
  def create
    @current_user = current_user
    @ticket = Ticket.new(ticket_params)
    @ticket.week_number = @ticket.week_date&.cweek
    @ticket.year = @ticket.week_date&.year
    respond_to do |format|
      if @ticket.save
        @ticket.send_ticket_created_email(current_user)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully created." }
        format.json { render :show, status: :created, location: @ticket }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tickets/1 or /tickets/1.json
  def update
    @current_user = current_user
    respond_to do |format|
      week_date = Date.parse(ticket_params[:week_date])&.cweek
      year = Date.parse(ticket_params[:week_date])&.year
      if @ticket.update(ticket_params.merge(week_number: week_date, year: year))
        @ticket.send_ticket_created_email(current_user)
        format.html { redirect_to ticket_url(@ticket), notice: "Ticket was successfully updated." }
        format.json { render :show, status: :ok, location: @ticket }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @ticket.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tickets/1 or /tickets/1.json
  def destroy
    @ticket.destroy

    respond_to do |format|
      format.html { redirect_to tickets_url, notice: "Ticket was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
#     def set_ticket
#       @ticket = Ticket.find(params[:id])
#     end

#     # Only allow a list of trusted parameters through.
#     # def ticket_params
#     #   params.require(:ticket).permit(:user_id, :booked_count, :extra_charges, :week_date, :booked_by_id, :booked_for_id)
#     # end
# def ticket_params
#   params.require(:ticket).permit(:user_id, :booked_count, :extra_charges, :price_per_ticket, :week_date, :booked_by_id, :booked_for_id)
# end
def set_ticket
      @ticket = Ticket.find(params[:id])
      unless @ticket.booked_by_id == current_user.id || @ticket.booked_for_id == current_user.id
        redirect_to root_path, alert: "You are not authorized to view this ticket."
      end
    end

    # Only allow a list of trusted parameters through.
    def ticket_params
      params.require(:ticket).permit(:user_id, :booked_count, :extra_charges, :price_per_ticket, :week_date, :booked_by_id, :booked_for_id)
    end

end

app/helpers/tickets_helper.rb
module TicketsHelper
end

app/views/tickets/_form.html.erb
<!-- app/views/tickets/_form.html.erb -->
<style>
  .ticket-form {
    max-width: 500px;
    margin: auto;
    padding: 20px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
    background-color: #fff;
  }

  #error_explanation {
    color: #dc3545;
    margin-bottom: 20px;
  }

  .form-group {
    margin-bottom: 20px;
  }

  .form-label {
    display: block;
    margin-bottom: 5px;
    font-weight: bold;
  }

  .form-control {
    width: 100%;
    padding: 10px;
    box-sizing: border-box;
    border: 1px solid #ccc;
    border-radius: 4px;
    font-size: 16px;
  }

  .btn-primary {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    cursor: pointer;
  }

  .btn-secondary {
    background-color: lightblue;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    cursor: pointer;
  }
  .custom-add-to-cart-btn {
    background-color: #808080 !important;
    height: 35px; 
    border-radius: 5px !important; 
  }
  .custom-add-to-cart-btn:hover {
    height: 35px;
    background-color: lightblue;
    color: white; 
    border-color: black;
  }
</style>

<%= form_with(model: ticket, local: true) do |form| %>
  <div class="ticket-form">
    <% if ticket.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h4><%= pluralize(ticket.errors.count, "error") %> prohibited this ticket from being saved:</h4>

        <ul>
          <% ticket.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <label for="user_id" class="form-label">Select User</label>
      <%#= form.collection_select :user_id, User.all, :id, :name, { prompt: 'Select User' }, class: 'form-control' %>
      <%= form.collection_select :user_id, [current_user], :id, :name, { prompt: 'Select User' }, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label for="booked_by_id" class="form-label">Select booked by user</label>
      <%#= form.collection_select :booked_by_id, User.all, :id, :name, { prompt: 'Select booked by user' }, class: 'form-control' %>
      <%= form.collection_select :booked_by_id, [current_user], :id, :name, { prompt: 'Select booked by user' }, class: 'form-control' %>
    </div>

    <div class="form-group">
      <label for="booked_for_id" class="form-label">Select booked for user</label>
      <%= form.collection_select :booked_for_id, User.where.not(id: current_user.id), :id, :name, { prompt: 'Select booked for user' }, class: 'form-control' %>
      <%#= form.collection_select :booked_for_id, User.all, :id, :name, { prompt: 'Select booked for user' }, class: 'form-control' %>
    </div>

    <div  style="display: flex;">
      <div class="form-group">
      <label for="booked_count" class="form-label">Number of tickets booked</label>
      <%= form.number_field :booked_count, class: 'form-control', placeholder: 'Number of tickets booked' %>
      </div>
      <div class="form-group">
        <label for="price_per_ticket" class="form-label">Price per ticket</label>
        <%= form.number_field :price_per_ticket, class: 'form-control', placeholder: 'Price per ticket', step: 'any', value: (ticket.new_record? ? 85 : ticket.price_per_ticket) %>
      </div>
    </div>

   

    <div class="form-group">
      <label for="extra_charges" class="form-label">Extra charges</label>
      <%= form.number_field :extra_charges, step: 0.01, class: 'form-control', placeholder: 'Extra charges' %>
    </div>

    <div class="form-group">
      <label for="week_date" class="form-label">Week date</label>
      <%= form.date_field :week_date, class: 'form-control', placeholder: 'Week date' %>
      <%#= form.hidden_field :week_number, value: (ticket.week_date ? ticket.week_date.cweek : nil) %>
      <%#= form.hidden_field :year, value: (ticket.week_date ? ticket.week_date.year : nil) %>
    </div>
    <center>
    <div class="actions">
      <%= form.submit 'Create Ticket', class: "btn btn-outline-light btn-block mt-3 custom-add-to-cart-btn" %>
      <%= link_to 'Cancel', tickets_path, class: 'btn btn-secondary' %>
    </div>
    </center>
  </div>
<% end %>

app/views/tickets/edit.html.erb
<center><h2>Tickets</h2>

<%= render 'form', ticket: @ticket %>

<div class="actions">
    <%= link_to 'Home', root_path, class: 'btn btn-secondary' %>
    <%= link_to 'Back', tickets_path, class: 'btn btn-secondary' %>
</div></center>

app/views/tickets/index.html.erb
<!-- app/views/tickets/index.html.erb -->
<div id="tickets-list">
  <p id="notice"><%= notice %></p>

  <center><h2>Tickets</h2>
  <%if @tickets.present?%>
  <table>

      <tr>
        <th>Booked By</th>
        <th>Booked For</th>
        <th>Total Booked</th>
        <th>Per Ticket Price</th>
        <th>Total Amount (exl. EC)</th>
        <th>Extra Charges(EC)</th>
        <th>Week Date</th>
        <th>Actions</th>
      </tr>

    <tbody>
      <% @tickets.each do |ticket| %>
        <tr>
          <td><%= ticket.booked_by.name %></td>
          <td><%= ticket.booked_for.name %></td>
          <td><%= ticket.booked_count %></td>
          <td>₹<%= ticket.price_per_ticket %></td>
          <td>₹<%= ticket.price_per_ticket * ticket.booked_count %></td>
          <td>₹<%= ticket.extra_charges %></td>
          <td><%= ticket.week_date %></td>
          <td>
            <%= link_to 'Show', ticket, class: 'btn btn-primary' %>
            <%= link_to 'Edit', edit_ticket_path(ticket), class: 'btn btn-secondary' %>
            <%#= button_to 'Destroy', ticket, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn btn-danger' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%else%>
    <h3>No tickets found!</h3>
  <%end%>
  <div class="actions">
    <%= link_to 'New Ticket', new_ticket_path, class: 'btn btn-primary' %>
    <%= link_to 'Home', root_path, class: 'btn btn-secondary' %>
  </div>
</div>
</center>

app/views/tickets/new.html.erb
<!-- app/views/tickets/new.html.erb -->
<div id="new-ticket">
  <center><h2>Create New Tickets</h2>

  <%= render 'form', ticket: @ticket %>

  <div class="actions">
    <%= link_to 'Home', root_path, class: 'btn btn-secondary' %>
    <%= link_to 'Back', tickets_path, class: 'btn btn-secondary' %>
  </div></center>
</div>

app/views/tickets/show.html.erb
<!-- app/views/tickets/show.html.erb -->
<div id="ticket-details">
  <center>
  <h2>Ticket Details</h2>

  <% if @ticket.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@ticket.errors.count, "error") %> prohibited this ticket from being saved:</h2>

      <ul>
        <% @ticket.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="ticket-info">
    <tr>
      <th>Attribute</th>
      <th>Value</th>
    </tr>
    <tr>
      <td><strong>Booked by:</strong></td>
      <td><%= @ticket.booked_by.name %></td>
    </tr>
    <tr>
      <td><strong>Booked for:</strong></td>
      <td><%= @ticket.booked_for.name %></td>
    </tr>
    <tr>
      <td><strong>Total Booked:</strong></td>
      <td><%= @ticket.booked_count %></td>
    </tr>
    <tr>
      <td><strong>Week Date:</strong></td>
      <td><%= @ticket.week_date %></td>
    </tr>
    <tr>
      <td><strong>Per Ticket Price:</strong></td>
      <td>₹<%= @ticket.price_per_ticket %></td>
    </tr>
    <tr>
      <td><strong>Extra Charges(EC):</strong></td>
      <td>₹<%= @ticket.extra_charges %></td>
    </tr>
    <tr>
      <td><strong>Total Amount (exl. EC):</strong></td>
      <td>₹<%= @ticket.price_per_ticket * @ticket.booked_count %></td>
    </tr>
  </table>

  <div class="actions">
    <%= link_to 'Edit Ticket', edit_ticket_path(@ticket), class: 'btn btn-primary' %> 
    <%= link_to 'Back to Tickets', tickets_path, class: 'btn btn-secondary' %> 
    <%= link_to 'Home', root_path, class: 'btn btn-secondary' %>
  </div>
  </center>
</div>