config/routes.rb
Rails.application.routes.draw do
  get 'make_my_trip_bookings/new'
  get 'make_my_trip_bookings/search', to: 'make_my_trip_bookings#search', as: :search_buses
  get 'make_my_trip_bookings/search_suggestion'
  get 'ticket_bookings/new'
  get 'ticket_bookings/create'
  devise_for :users
  ActiveAdmin.routes(self)
  root to: "home#index"
  resources :payments
  get 'home/index'
  resources :tickets do
    resources :ticket_bookings, only: [:new, :create]
  end
  resources :users do
    get 'my_tickets', on: :collection
  end
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/payment.rb
class Payment < ApplicationRecord
  # after_create :send_payment_created_email
  # after_update :send_payment_created_email

  belongs_to :paid_by, class_name: 'User', foreign_key: 'paid_by_id'
  belongs_to :paid_to, class_name: 'User', foreign_key: 'paid_to_id'
 
  # private
  def send_payment_created_email(current_user)
    paid_by = User.find(self.paid_by_id)
    paid_to = User.find(self.paid_to_id)
    PaymentMailer.payment_created_email(self, HomeController.calculate_owe_summary(paid_by), paid_by).deliver_now
    PaymentMailer.payment_created_email(self, HomeController.calculate_owe_summary(paid_to), paid_to).deliver_now
    # PaymentMailer.payment_created_email(self, HomeController.calculate_owe_summary(current_user), current_user).deliver_now
  end
end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :authenticate_user!
  before_action :set_payment, only: %i[ show edit update destroy ]

  # GET /payments or /payments.json
  # def index
  #   @payments = Payment.all
  # end
  def index
    @payments = Payment.where("paid_to_id = ? OR paid_by_id = ?", current_user.id, current_user.id)
  end

  # GET /payments/1 or /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments or /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        @payment.send_payment_created_email(current_user)
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully created." }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1 or /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        @payment.send_payment_created_email(current_user)
        format.html { redirect_to payment_url(@payment), notice: "Payment was successfully updated." }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1 or /payments/1.json
  def destroy
    @payment.destroy

    respond_to do |format|
      format.html { redirect_to payments_url, notice: "Payment was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # def set_payment
    #   @payment = Payment.find(params[:id])
    # end

    # def payment_params
    #   params.require(:payment).permit(:paid_to_id, :paid_by_id, :amount, :date)
    # end
    
    def set_payment
      @payment = Payment.find(params[:id])
      unless @payment.paid_to_id == current_user.id || @payment.paid_by_id == current_user.id
        redirect_to root_path, alert: "You are not authorized to view this payment."
      end
    end

    def payment_params
      params.require(:payment).permit(:paid_to_id, :paid_by_id, :amount, :date)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper
end

app/views/payments/_form.html.erb
<!-- app/views/payments/_form.html.erb -->
<style>
  .form-container {
    max-width: 500px;
    margin: auto;
    padding: 20px;
    box-shadow: 0 4px 8px rgba(0, 0, 0, 0.1);
    border-radius: 8px;
    background-color: #fff;
  }

  #error_explanation {
    color: #dc3545;
    margin-bottom: 20px;
  }

  .form-group {
    margin-bottom: 20px;
  }

  .form-label {
    font-weight: bold;
    display: block;
    margin-bottom: 5px;
  }

  .form-control {
    width: 100%;
    padding: 10px;
    box-sizing: border-box;
    border: 1px solid #ccc;
    border-radius: 4px;
    margin-top: 5px; /* Adjust the top margin as needed */
    font-size: 16px;
  }

  .btn-primary {
    background-color: #007bff;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    cursor: pointer;
  }

  .btn-secondary {
    background-color: lightblue;
    color: #fff;
    border: none;
    padding: 10px 20px;
    border-radius: 4px;
    cursor: pointer;
  }
  .custom-add-to-cart-btn {
    background-color: #808080 !important;
    height: 35px; 
    border-radius: 5px !important; 
  }
  .custom-add-to-cart-btn:hover {
    height: 35px;
    background-color: lightblue;
    color: white; 
    border-color: black;
  }
</style>

<%= form_with(model: payment, local: true) do |form| %>
  <div class="form-container">
    <% if payment.errors.any? %>
      <div id="error_explanation" class="alert alert-danger">
        <h4><%= pluralize(payment.errors.count, "error") %> prohibited this ticket from being saved:</h4>

        <ul>
          <% payment.errors.each do |error| %>
            <li><%= error.full_message %></li>
          <% end %>
        </ul>
      </div>
    <% end %>

    <div class="form-group">
      <%= form.label :paid_by, 'Select payment by', class: 'form-label' %>
      <%= form.collection_select :paid_by_id, User.all, :id, :name, prompt: 'Select paid by user', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :paid_to, 'Select payment to', class: 'form-label' %>
      <%= form.collection_select :paid_to_id, User.all, :id, :name, prompt: 'Select paid to user', class: 'form-control' %>
    </div>

    <div class="form-group">
      <%= form.label :amount, 'Amount', class: 'form-label' %>
      <%= form.number_field :amount, class: 'form-control', placeholder: 'Amount' %>
    </div>

    <div class="form-group">
      <%= form.label :date, 'Date of payment', class: 'form-label' %>
      <%= form.date_field :date, class: 'form-control', placeholder: 'Week date' %>
    </div>

    <div class="actions">
      <%= form.submit 'Create Payment', class: "btn btn-outline-light btn-block mt-3 custom-add-to-cart-btn" %>
      <%= link_to 'Cancel', payments_path, class: 'btn btn-secondary' %>
    </div>
  </div>
<% end %>

app/views/payments/edit.html.erb
<center><h2>Editing Payment</h2>

<%= render 'form', payment: @payment %>

<div class="actions">
    <%= link_to 'Home', root_path, class: 'btn btn-secondary' %>
    <%= link_to 'Back', payments_path, class: 'btn btn-secondary' %>
</div></center>

app/views/payments/index.html.erb
<!-- app/views/tickets/index.html.erb -->
<div id="tickets-list">
  <center>
  <p id="notice"><%= notice %></p>

  <h2>Payments</h2>
  <%if @payments.present?%>
  <table>

      <tr>
        <%# <th>User</th> %>
        <th>Paid By</th>
        <th>Paid To</th>
        <th>Amount</th>
        <th>Date</th>
        <th>Actions</th>
      </tr>


    <tbody>
      <% @payments.each do |payment| %>
        <tr>
          <td><%= payment.paid_by.name %></td>
          <td><%= payment.paid_to.name %></td>
          <td><%= payment.amount %></td>
          <td><%= payment.date %></td>
          <td>
          <%= link_to 'Show', payment, class: 'btn' %>
          <%= link_to 'Edit', edit_payment_path(payment), class: 'btn' %>
          <%#= button_to 'Destroy', payment, method: :delete, data: { confirm: 'Are you sure?' }, class: 'btn' %>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%else%>
    <h3>No payments found!</h3>
  <%end%>
  <div class="actions">
    <%= link_to 'New Payment', new_payment_path, class: 'btn' %>
    <%= link_to 'New Ticket', new_ticket_path, class: 'btn' %>
    <%= link_to 'Home', root_path, class: 'btn' %>
  </div>
  </center>
</div>

app/views/payments/new.html.erb
<center><h2>Create New Payment</h2>
<%= render 'form', payment: @payment %>

<div class="actions">
    <%= link_to 'Home', root_path, class: 'btn btn-secondary' %>
    <%= link_to 'Back', tickets_path, class: 'btn btn-secondary' %>
</div>
</center>

app/views/payments/show.html.erb
<!-- app/views/payments/show.html.erb -->
<div id="payment-details">
  <center><h2>Payment Details</h2>

  <% if @payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h2>

      <ul>
        <% @payment.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <table class="payment-info">
    <tr>
      <th>Attribute</th>
      <th>Value</th>
    </tr>
    <tr>
      <td><strong>Paid by:</strong></td>
      <td><%= @payment.paid_by.name %></td>
    </tr>
    <tr>
      <td><strong>Paid to:</strong></td>
      <td><%= @payment.paid_to.name %></td>
    </tr>
    <tr>
      <td><strong>Amount:</strong></td>
      <td><%= @payment.amount %></td>
    </tr>
    <tr>
      <td><strong>Date:</strong></td>
      <td><%= @payment.date %></td>
    </tr>
  </table>

  <div class="actions">
    <%= link_to 'Edit Payment', edit_payment_path(@payment), class: 'btn btn-primary' %> 
    <%= link_to 'Back to Payments', payments_path, class: 'btn btn-secondary' %> 
    <%= link_to 'Home', root_path, class: 'btn btn-secondary' %>
  </div>
</center>
</div>
  